# Generated by Django 3.2.9 on 2022-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
